package WWW::SwaggerClient::Object::Conversion;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
      'id' => 'string',
      'target' => 'string',
      'category' => 'string',
      'options' => 'object'
};

my $attribute_map = {
      'id' => 'id',
      'target' => 'target',
      'category' => 'category',
      'options' => 'options'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #Identifier for the job conversion.
        'id' => $args{'id'}, 
        #Identifier for the job conversion type.
        'target' => $args{'target'}, 
        #Category for the conveted file.
        'category' => $args{'category'}, 
        #Type of conversion to perform with the file.
        'options' => $args{'options'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
  return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
  return $attribute_map;
}

1;
