package WWW::SwaggerClient::Object::Conversion;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->class_documentation({description => '',
                                  class => 'Conversion',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
    	datatype => 'string',
    	base_name => 'id',
    	description => 'Identifier for the job conversion.',
    	format => '',
    	read_only => '',
    		},
    'target' => {
    	datatype => 'string',
    	base_name => 'target',
    	description => 'Identifier for the job conversion type.',
    	format => '',
    	read_only => '',
    		},
    'category' => {
    	datatype => 'string',
    	base_name => 'category',
    	description => 'Category for the conveted file.',
    	format => '',
    	read_only => '',
    		},
    'options' => {
    	datatype => 'object',
    	base_name => 'options',
    	description => 'Type of conversion to perform with the file.',
    	format => '',
    	read_only => '',
    		},
    
});

__PACKAGE__->swagger_types( {
    'id' => 'string',
    'target' => 'string',
    'category' => 'string',
    'options' => 'object'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'target' => 'target',
    'category' => 'category',
    'options' => 'options'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});

1;
