package WWW::SwaggerClient::Object::Error;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->class_documentation({description => '',
                                  class => 'Error',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'code' => {
    	datatype => 'int',
    	base_name => 'code',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message' => {
    	datatype => 'string',
    	base_name => 'message',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'errors' => {
    	datatype => 'object',
    	base_name => 'errors',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    
});

__PACKAGE__->swagger_types( {
    'code' => 'int',
    'message' => 'string',
    'errors' => 'object'
} );

__PACKAGE__->attribute_map( {
    'code' => 'code',
    'message' => 'message',
    'errors' => 'errors'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});

1;
