package WWW::SwaggerClient::Object::History;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->class_documentation({description => '',
                                  class => 'History',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
    	datatype => 'string',
    	base_name => 'id',
    	description => 'Unique identifier of the event.',
    	format => '',
    	read_only => '',
    		},
    'status' => {
    	datatype => 'string',
    	base_name => 'status',
    	description => 'Status of the job.',
    	format => '',
    	read_only => '',
    		},
    'info' => {
    	datatype => 'string',
    	base_name => 'info',
    	description => 'Addtional information.',
    	format => '',
    	read_only => '',
    		},
    'created_at' => {
    	datatype => 'DateTime',
    	base_name => 'created_at',
    	description => 'Date and time when the job was created.',
    	format => '',
    	read_only => '',
    		},
    
});

__PACKAGE__->swagger_types( {
    'id' => 'string',
    'status' => 'string',
    'info' => 'string',
    'created_at' => 'DateTime'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'status' => 'status',
    'info' => 'info',
    'created_at' => 'created_at'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});

1;
