package WWW::SwaggerClient::Object::InputFile;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
      'id' => 'string',
      'type' => 'string',
      'source' => 'string',
      'filename' => 'string',
      'size' => 'int',
      'created_at' => 'DateTime',
      'modified_at' => 'DateTime'
};

my $attribute_map = {
      'id' => 'id',
      'type' => 'type',
      'source' => 'source',
      'filename' => 'filename',
      'size' => 'size',
      'created_at' => 'created_at',
      'modified_at' => 'modified_at'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #Unique identifier for the file.
        'id' => $args{'id'}, 
        #How the file has been generated.
        'type' => $args{'type'}, 
        #The source of the file to be used that can be either, an external url. An identifier for an uploaded file to the server or an identifier for another job.
        'source' => $args{'source'}, 
        #Filename of the file.
        'filename' => $args{'filename'}, 
        #Size of the file in bytes.
        'size' => $args{'size'}, 
        #Date and time when the job was created.
        'created_at' => $args{'created_at'}, 
        #Date and time when the job was last modified.
        'modified_at' => $args{'modified_at'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
  return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
  return $attribute_map;
}

1;
