package WWW::SwaggerClient::Object::InputFile;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->class_documentation({description => '',
                                  class => 'InputFile',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
    	datatype => 'string',
    	base_name => 'id',
    	description => 'Unique identifier for the file.',
    	format => '',
    	read_only => '',
    		},
    'type' => {
    	datatype => 'string',
    	base_name => 'type',
    	description => 'How the file has been generated.',
    	format => '',
    	read_only => '',
    		},
    'source' => {
    	datatype => 'string',
    	base_name => 'source',
    	description => 'The source of the file to be used that can be either, an external url. An identifier for an uploaded file to the server or an identifier for another job.',
    	format => '',
    	read_only => '',
    		},
    'filename' => {
    	datatype => 'string',
    	base_name => 'filename',
    	description => 'Filename of the file.',
    	format => '',
    	read_only => '',
    		},
    'size' => {
    	datatype => 'int',
    	base_name => 'size',
    	description => 'Size of the file in bytes.',
    	format => '',
    	read_only => '',
    		},
    'hash' => {
    	datatype => 'string',
    	base_name => 'hash',
    	description => 'File hash for content verification',
    	format => '',
    	read_only => '',
    		},
    'content_type' => {
    	datatype => 'string',
    	base_name => 'content_type',
    	description => 'Content type for file conversion definition',
    	format => '',
    	read_only => '',
    		},
    'created_at' => {
    	datatype => 'DateTime',
    	base_name => 'created_at',
    	description => 'Date and time when the job was created.',
    	format => '',
    	read_only => '',
    		},
    'modified_at' => {
    	datatype => 'DateTime',
    	base_name => 'modified_at',
    	description => 'Date and time when the job was last modified.',
    	format => '',
    	read_only => '',
    		},
    
});

__PACKAGE__->swagger_types( {
    'id' => 'string',
    'type' => 'string',
    'source' => 'string',
    'filename' => 'string',
    'size' => 'int',
    'hash' => 'string',
    'content_type' => 'string',
    'created_at' => 'DateTime',
    'modified_at' => 'DateTime'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'type' => 'type',
    'source' => 'source',
    'filename' => 'filename',
    'size' => 'size',
    'hash' => 'hash',
    'content_type' => 'content_type',
    'created_at' => 'created_at',
    'modified_at' => 'modified_at'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});

1;
