package WWW::SwaggerClient::Object::Job;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
      'id' => 'string',
      'token' => 'string',
      'type' => 'string',
      'status' => 'Status',
      'process' => 'boolean',
      'conversion' => 'ARRAY[Conversion]',
      'input' => 'ARRAY[InputFile]',
      'callback' => 'string',
      'server' => 'string',
      'created_at' => 'DateTime',
      'modified_at' => 'DateTime'
};

my $attribute_map = {
      'id' => 'id',
      'token' => 'token',
      'type' => 'type',
      'status' => 'status',
      'process' => 'process',
      'conversion' => 'conversion',
      'input' => 'input',
      'callback' => 'callback',
      'server' => 'server',
      'created_at' => 'created_at',
      'modified_at' => 'modified_at'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #Unique identifier for the job.
        'id' => $args{'id'}, 
        #Token to identify client allowed to run the job.
        'token' => $args{'token'}, 
        #Type of the job created.
        'type' => $args{'type'}, 
        #Current status for the job
        'status' => $args{'status'}, 
        #Determine if the job must be processed as soon as it is ready.
        'process' => $args{'process'}, 
        #Type of conversion or conversions to be carried out.
        'conversion' => $args{'conversion'}, 
        #Source or sources of the files to be converted.
        'input' => $args{'input'}, 
        #Callback url to the the status updates
        'callback' => $args{'callback'}, 
        #Server assigned for file uploads and downloads
        'server' => $args{'server'}, 
        #Date and time when the job was created.
        'created_at' => $args{'created_at'}, 
        #Date and time when the job was last modified.
        'modified_at' => $args{'modified_at'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
  return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
  return $attribute_map;
}

1;
