package WWW::SwaggerClient::Object::Job;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->class_documentation({description => '',
                                  class => 'Job',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
    	datatype => 'string',
    	base_name => 'id',
    	description => 'Unique identifier for the job.',
    	format => '',
    	read_only => '',
    		},
    'token' => {
    	datatype => 'string',
    	base_name => 'token',
    	description => 'Token to identify client allowed to run the job.',
    	format => '',
    	read_only => '',
    		},
    'type' => {
    	datatype => 'string',
    	base_name => 'type',
    	description => 'Type of the job created.',
    	format => '',
    	read_only => '',
    		},
    'status' => {
    	datatype => 'Status',
    	base_name => 'status',
    	description => 'Current status for the job',
    	format => '',
    	read_only => '',
    		},
    'process' => {
    	datatype => 'boolean',
    	base_name => 'process',
    	description => 'Determine if the job must be processed as soon as it is ready.',
    	format => '',
    	read_only => '',
    		},
    'conversion' => {
    	datatype => 'ARRAY[Conversion]',
    	base_name => 'conversion',
    	description => 'Type of conversion or conversions to be carried out.',
    	format => '',
    	read_only => '',
    		},
    'input' => {
    	datatype => 'ARRAY[InputFile]',
    	base_name => 'input',
    	description => 'Source or sources of the files to be converted.',
    	format => '',
    	read_only => '',
    		},
    'output' => {
    	datatype => 'ARRAY[OutputFile]',
    	base_name => 'output',
    	description => 'Output or Outputs of the conversion.',
    	format => '',
    	read_only => '',
    		},
    'callback' => {
    	datatype => 'string',
    	base_name => 'callback',
    	description => 'Callback url to the the status updates',
    	format => '',
    	read_only => '',
    		},
    'server' => {
    	datatype => 'string',
    	base_name => 'server',
    	description => 'Server assigned for file uploads and downloads',
    	format => '',
    	read_only => '',
    		},
    'spent' => {
    	datatype => 'int',
    	base_name => 'spent',
    	description => 'Converion minutes spent to complete the job',
    	format => '',
    	read_only => '',
    		},
    'created_at' => {
    	datatype => 'DateTime',
    	base_name => 'created_at',
    	description => 'Date and time when the job was created.',
    	format => '',
    	read_only => '',
    		},
    'modified_at' => {
    	datatype => 'DateTime',
    	base_name => 'modified_at',
    	description => 'Date and time when the job was last modified.',
    	format => '',
    	read_only => '',
    		},
    
});

__PACKAGE__->swagger_types( {
    'id' => 'string',
    'token' => 'string',
    'type' => 'string',
    'status' => 'Status',
    'process' => 'boolean',
    'conversion' => 'ARRAY[Conversion]',
    'input' => 'ARRAY[InputFile]',
    'output' => 'ARRAY[OutputFile]',
    'callback' => 'string',
    'server' => 'string',
    'spent' => 'int',
    'created_at' => 'DateTime',
    'modified_at' => 'DateTime'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'token' => 'token',
    'type' => 'type',
    'status' => 'status',
    'process' => 'process',
    'conversion' => 'conversion',
    'input' => 'input',
    'output' => 'output',
    'callback' => 'callback',
    'server' => 'server',
    'spent' => 'spent',
    'created_at' => 'created_at',
    'modified_at' => 'modified_at'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});

1;
