package WWW::SwaggerClient::Object::OutputFile;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
      'id' => 'string',
      'source' => 'object',
      'uri' => 'string',
      'filename' => 'string',
      'size' => 'int',
      'created_at' => 'DateTime'
};

my $attribute_map = {
      'id' => 'id',
      'source' => 'source',
      'uri' => 'uri',
      'filename' => 'filename',
      'size' => 'size',
      'created_at' => 'created_at'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #Unique identifier for the file.
        'id' => $args{'id'}, 
        #Sources for the files including the input files and conversion used.
        'source' => $args{'source'}, 
        #Url for downloading the file.
        'uri' => $args{'uri'}, 
        #Filename of the file.
        'filename' => $args{'filename'}, 
        #Size of the file in bytes.
        'size' => $args{'size'}, 
        #Date and time when the job was created.
        'created_at' => $args{'created_at'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
  return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
  return $attribute_map;
}

1;
