package WWW::SwaggerClient::Object::OutputFileSource;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#Sources for the files including the input files and conversion used.
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->class_documentation({description => 'Sources for the files including the input files and conversion used.',
                                  class => 'OutputFileSource',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'input' => {
    	datatype => 'ARRAY[string]',
    	base_name => 'input',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'conversion' => {
    	datatype => 'string',
    	base_name => 'conversion',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    
});

__PACKAGE__->swagger_types( {
    'input' => 'ARRAY[string]',
    'conversion' => 'string'
} );

__PACKAGE__->attribute_map( {
    'input' => 'input',
    'conversion' => 'conversion'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});

1;
