package WWW::SwaggerClient::Object::Status;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->class_documentation({description => '',
                                  class => 'Status',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'code' => {
    	datatype => 'string',
    	base_name => 'code',
    	description => 'Status code identifier.',
    	format => '',
    	read_only => '',
    		},
    'info' => {
    	datatype => 'string',
    	base_name => 'info',
    	description => 'Description of the status code.',
    	format => '',
    	read_only => '',
    		},
    
});

__PACKAGE__->swagger_types( {
    'code' => 'string',
    'info' => 'string'
} );

__PACKAGE__->attribute_map( {
    'code' => 'code',
    'info' => 'info'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});

1;
