package WWW::SwaggerClient::Object::Thread;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->class_documentation({description => '',
                                  class => 'Thread',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'hash' => {
    	datatype => 'string',
    	base_name => 'hash',
    	description => 'Unique identifier of the thread.',
    	format => '',
    	read_only => '',
    		},
    'status' => {
    	datatype => 'int',
    	base_name => 'status',
    	description => 'Status of the thread.',
    	format => '',
    	read_only => '',
    		},
    'info' => {
    	datatype => 'string',
    	base_name => 'info',
    	description => 'Extra information.',
    	format => '',
    	read_only => '',
    		},
    'exec_time' => {
    	datatype => 'int',
    	base_name => 'exec_time',
    	description => 'Execution time for the thread in seconds',
    	format => '',
    	read_only => '',
    		},
    'created_at' => {
    	datatype => 'DateTime',
    	base_name => 'created_at',
    	description => 'Date and time when the job was created.',
    	format => '',
    	read_only => '',
    		},
    'modified_at' => {
    	datatype => 'DateTime',
    	base_name => 'modified_at',
    	description => 'Date and time when the job was last modified.',
    	format => '',
    	read_only => '',
    		},
    
});

__PACKAGE__->swagger_types( {
    'hash' => 'string',
    'status' => 'int',
    'info' => 'string',
    'exec_time' => 'int',
    'created_at' => 'DateTime',
    'modified_at' => 'DateTime'
} );

__PACKAGE__->attribute_map( {
    'hash' => 'hash',
    'status' => 'status',
    'info' => 'info',
    'exec_time' => 'exec_time',
    'created_at' => 'created_at',
    'modified_at' => 'modified_at'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});

1;
